url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

description: >-

# Do not force-enable plugins from the theme. Add plugin names in the site's _config.yml.
# Example site _config.yml:
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap

exclude:
  - jekyll-mumbela-theme.gemspec
  - LICENSE.txt
  - README.txt
